#![allow(non_snake_case)]

use super::{emu::GameBoyEmulator, utils::*, prefixed_instructions::PrefixedInstruction};
use num_enum::FromPrimitive;

impl GameBoyEmulator {
    /// Run immediate prefixed operation `n8`.
    pub fn PREFIX_n8(&mut self) {
        let op = self.read_u8(RegisterPair::PC);
        match PrefixedInstruction::from_primitive(op) {
            // * 0x0_
            PrefixedInstruction::RLC_B => self.RLC_r8(Register::B),
            PrefixedInstruction::RLC_C => self.RLC_r8(Register::C),
            PrefixedInstruction::RLC_D => self.RLC_r8(Register::D),
            PrefixedInstruction::RLC_E => self.RLC_r8(Register::E),
            PrefixedInstruction::RLC_H => self.RLC_r8(Register::H),
            PrefixedInstruction::RLC_L => self.RLC_r8(Register::L),
            PrefixedInstruction::RLC_HL => self.RLC_r16(RegisterPair::HL),
            PrefixedInstruction::RLC_A => self.RLC_r8(Register::A),
            PrefixedInstruction::RRC_B => self.RRC_r8(Register::B),
            PrefixedInstruction::RRC_C => self.RRC_r8(Register::C),
            PrefixedInstruction::RRC_D => self.RRC_r8(Register::D),
            PrefixedInstruction::RRC_E => self.RRC_r8(Register::E),
            PrefixedInstruction::RRC_H => self.RRC_r8(Register::H),
            PrefixedInstruction::RRC_L => self.RRC_r8(Register::L),
            PrefixedInstruction::RRC_HL => self.RRC_r16(RegisterPair::HL),
            PrefixedInstruction::RRC_A => self.RRC_r8(Register::A),
            // * 0x1_
            PrefixedInstruction::RL_B => self.RL_r8(Register::B),
            PrefixedInstruction::RL_C => self.RL_r8(Register::C),
            PrefixedInstruction::RL_D => self.RL_r8(Register::D),
            PrefixedInstruction::RL_E => self.RL_r8(Register::E),
            PrefixedInstruction::RL_H => self.RL_r8(Register::H),
            PrefixedInstruction::RL_L => self.RL_r8(Register::L),
            PrefixedInstruction::RL_HL => self.RL_r16(RegisterPair::HL),
            PrefixedInstruction::RL_A => self.RL_r8(Register::A),
            PrefixedInstruction::RR_B => self.RR_r8(Register::B),
            PrefixedInstruction::RR_C => self.RR_r8(Register::C),
            PrefixedInstruction::RR_D => self.RR_r8(Register::D),
            PrefixedInstruction::RR_E => self.RR_r8(Register::E),
            PrefixedInstruction::RR_H => self.RR_r8(Register::H),
            PrefixedInstruction::RR_L => self.RR_r8(Register::L),
            PrefixedInstruction::RR_HL => self.RR_r16(RegisterPair::HL),
            PrefixedInstruction::RR_A => self.RR_r8(Register::A),
            // * 0x2_
            PrefixedInstruction::SLA_B => self.SLA_r8(Register::B),
            PrefixedInstruction::SLA_C => self.SLA_r8(Register::C),
            PrefixedInstruction::SLA_D => self.SLA_r8(Register::D),
            PrefixedInstruction::SLA_E => self.SLA_r8(Register::E),
            PrefixedInstruction::SLA_H => self.SLA_r8(Register::H),
            PrefixedInstruction::SLA_L => self.SLA_r8(Register::L),
            PrefixedInstruction::SLA_HL => self.SLA_r16(RegisterPair::HL),
            PrefixedInstruction::SLA_A => self.SLA_r8(Register::A),
            PrefixedInstruction::SRA_B => self.SRA_r8(Register::B),
            PrefixedInstruction::SRA_C => self.SRA_r8(Register::C),
            PrefixedInstruction::SRA_D => self.SRA_r8(Register::D),
            PrefixedInstruction::SRA_E => self.SRA_r8(Register::E),
            PrefixedInstruction::SRA_H => self.SRA_r8(Register::H),
            PrefixedInstruction::SRA_L => self.SRA_r8(Register::L),
            PrefixedInstruction::SRA_HL => self.SRA_r16(RegisterPair::HL),
            PrefixedInstruction::SRA_A => self.SRA_r8(Register::A),
            // * 0x3_
            PrefixedInstruction::SWAP_B => self.SWAP_r8(Register::B),
            PrefixedInstruction::SWAP_C => self.SWAP_r8(Register::C),
            PrefixedInstruction::SWAP_D => self.SWAP_r8(Register::D),
            PrefixedInstruction::SWAP_E => self.SWAP_r8(Register::E),
            PrefixedInstruction::SWAP_H => self.SWAP_r8(Register::H),
            PrefixedInstruction::SWAP_L => self.SWAP_r8(Register::L),
            PrefixedInstruction::SWAP_HL => self.SWAP_r16(RegisterPair::HL),
            PrefixedInstruction::SWAP_A => self.SWAP_r8(Register::A),
            PrefixedInstruction::SRL_B => self.SRL_r8(Register::B),
            PrefixedInstruction::SRL_C => self.SRL_r8(Register::C),
            PrefixedInstruction::SRL_D => self.SRL_r8(Register::D),
            PrefixedInstruction::SRL_E => self.SRL_r8(Register::E),
            PrefixedInstruction::SRL_H => self.SRL_r8(Register::H),
            PrefixedInstruction::SRL_L => self.SRL_r8(Register::L),
            PrefixedInstruction::SRL_HL => self.SRL_r16(RegisterPair::HL),
            PrefixedInstruction::SRL_A => self.SRL_r8(Register::A),
            // * 0x4_
            PrefixedInstruction::BIT_0_B => self.BIT_b_r8(0, Register::B),
            PrefixedInstruction::BIT_0_C => self.BIT_b_r8(0, Register::C),
            PrefixedInstruction::BIT_0_D => self.BIT_b_r8(0, Register::D),
            PrefixedInstruction::BIT_0_E => self.BIT_b_r8(0, Register::E),
            PrefixedInstruction::BIT_0_H => self.BIT_b_r8(0, Register::H),
            PrefixedInstruction::BIT_0_L => self.BIT_b_r8(0, Register::L),
            PrefixedInstruction::BIT_0_HL => self.BIT_b_r16(0, RegisterPair::HL),
            PrefixedInstruction::BIT_0_A => self.BIT_b_r8(0, Register::A),
            PrefixedInstruction::BIT_1_B => self.BIT_b_r8(1, Register::B),
            PrefixedInstruction::BIT_1_C => self.BIT_b_r8(1, Register::C),
            PrefixedInstruction::BIT_1_D => self.BIT_b_r8(1, Register::D),
            PrefixedInstruction::BIT_1_E => self.BIT_b_r8(1, Register::E),
            PrefixedInstruction::BIT_1_H => self.BIT_b_r8(1, Register::H),
            PrefixedInstruction::BIT_1_L => self.BIT_b_r8(1, Register::L),
            PrefixedInstruction::BIT_1_HL => self.BIT_b_r16(1, RegisterPair::HL),
            PrefixedInstruction::BIT_1_A => self.BIT_b_r8(1, Register::A),
            // * 0x5_
            PrefixedInstruction::BIT_2_B => self.BIT_b_r8(2, Register::B),
            PrefixedInstruction::BIT_2_C => self.BIT_b_r8(2, Register::C),
            PrefixedInstruction::BIT_2_D => self.BIT_b_r8(2, Register::D),
            PrefixedInstruction::BIT_2_E => self.BIT_b_r8(2, Register::E),
            PrefixedInstruction::BIT_2_H => self.BIT_b_r8(2, Register::H),
            PrefixedInstruction::BIT_2_L => self.BIT_b_r8(2, Register::L),
            PrefixedInstruction::BIT_2_HL => self.BIT_b_r16(2, RegisterPair::HL),
            PrefixedInstruction::BIT_2_A => self.BIT_b_r8(2, Register::A),
            PrefixedInstruction::BIT_3_B => self.BIT_b_r8(3, Register::B),
            PrefixedInstruction::BIT_3_C => self.BIT_b_r8(3, Register::C),
            PrefixedInstruction::BIT_3_D => self.BIT_b_r8(3, Register::D),
            PrefixedInstruction::BIT_3_E => self.BIT_b_r8(3, Register::E),
            PrefixedInstruction::BIT_3_H => self.BIT_b_r8(3, Register::H),
            PrefixedInstruction::BIT_3_L => self.BIT_b_r8(3, Register::L),
            PrefixedInstruction::BIT_3_HL => self.BIT_b_r16(3, RegisterPair::HL),
            PrefixedInstruction::BIT_3_A => self.BIT_b_r8(3, Register::A),
            // * 0x6_
            PrefixedInstruction::BIT_4_B => self.BIT_b_r8(4, Register::B),
            PrefixedInstruction::BIT_4_C => self.BIT_b_r8(4, Register::C),
            PrefixedInstruction::BIT_4_D => self.BIT_b_r8(4, Register::D),
            PrefixedInstruction::BIT_4_E => self.BIT_b_r8(4, Register::E),
            PrefixedInstruction::BIT_4_H => self.BIT_b_r8(4, Register::H),
            PrefixedInstruction::BIT_4_L => self.BIT_b_r8(4, Register::L),
            PrefixedInstruction::BIT_4_HL => self.BIT_b_r16(4, RegisterPair::HL),
            PrefixedInstruction::BIT_4_A => self.BIT_b_r8(4, Register::A),
            PrefixedInstruction::BIT_5_B => self.BIT_b_r8(5, Register::B),
            PrefixedInstruction::BIT_5_C => self.BIT_b_r8(5, Register::C),
            PrefixedInstruction::BIT_5_D => self.BIT_b_r8(5, Register::D),
            PrefixedInstruction::BIT_5_E => self.BIT_b_r8(5, Register::E),
            PrefixedInstruction::BIT_5_H => self.BIT_b_r8(5, Register::H),
            PrefixedInstruction::BIT_5_L => self.BIT_b_r8(5, Register::L),
            PrefixedInstruction::BIT_5_HL => self.BIT_b_r16(5, RegisterPair::HL),
            PrefixedInstruction::BIT_5_A => self.BIT_b_r8(5, Register::A),
            // * 0x7_
            PrefixedInstruction::BIT_6_B => self.BIT_b_r8(6, Register::B),
            PrefixedInstruction::BIT_6_C => self.BIT_b_r8(6, Register::C),
            PrefixedInstruction::BIT_6_D => self.BIT_b_r8(6, Register::D),
            PrefixedInstruction::BIT_6_E => self.BIT_b_r8(6, Register::E),
            PrefixedInstruction::BIT_6_H => self.BIT_b_r8(6, Register::H),
            PrefixedInstruction::BIT_6_L => self.BIT_b_r8(6, Register::L),
            PrefixedInstruction::BIT_6_HL => self.BIT_b_r16(6, RegisterPair::HL),
            PrefixedInstruction::BIT_6_A => self.BIT_b_r8(6, Register::A),
            PrefixedInstruction::BIT_7_B => self.BIT_b_r8(7, Register::B),
            PrefixedInstruction::BIT_7_C => self.BIT_b_r8(7, Register::C),
            PrefixedInstruction::BIT_7_D => self.BIT_b_r8(7, Register::D),
            PrefixedInstruction::BIT_7_E => self.BIT_b_r8(7, Register::E),
            PrefixedInstruction::BIT_7_H => self.BIT_b_r8(7, Register::H),
            PrefixedInstruction::BIT_7_L => self.BIT_b_r8(7, Register::L),
            PrefixedInstruction::BIT_7_HL => self.BIT_b_r16(7, RegisterPair::HL),
            PrefixedInstruction::BIT_7_A => self.BIT_b_r8(7, Register::A),
            // * 0x8_
            PrefixedInstruction::RES_0_B => self.RES_b_r8(0, Register::B),
            PrefixedInstruction::RES_0_C => self.RES_b_r8(0, Register::C),
            PrefixedInstruction::RES_0_D => self.RES_b_r8(0, Register::D),
            PrefixedInstruction::RES_0_E => self.RES_b_r8(0, Register::E),
            PrefixedInstruction::RES_0_H => self.RES_b_r8(0, Register::H),
            PrefixedInstruction::RES_0_L => self.RES_b_r8(0, Register::L),
            PrefixedInstruction::RES_0_HL => self.RES_b_r16(0, RegisterPair::HL),
            PrefixedInstruction::RES_0_A => self.RES_b_r8(0, Register::A),
            PrefixedInstruction::RES_1_B => self.RES_b_r8(1, Register::B),
            PrefixedInstruction::RES_1_C => self.RES_b_r8(1, Register::C),
            PrefixedInstruction::RES_1_D => self.RES_b_r8(1, Register::D),
            PrefixedInstruction::RES_1_E => self.RES_b_r8(1, Register::E),
            PrefixedInstruction::RES_1_H => self.RES_b_r8(1, Register::H),
            PrefixedInstruction::RES_1_L => self.RES_b_r8(1, Register::L),
            PrefixedInstruction::RES_1_HL => self.RES_b_r16(1, RegisterPair::HL),
            PrefixedInstruction::RES_1_A => self.RES_b_r8(1, Register::A),
            // * 0x9_
            PrefixedInstruction::RES_2_B => self.RES_b_r8(2, Register::B),
            PrefixedInstruction::RES_2_C => self.RES_b_r8(2, Register::C),
            PrefixedInstruction::RES_2_D => self.RES_b_r8(2, Register::D),
            PrefixedInstruction::RES_2_E => self.RES_b_r8(2, Register::E),
            PrefixedInstruction::RES_2_H => self.RES_b_r8(2, Register::H),
            PrefixedInstruction::RES_2_L => self.RES_b_r8(2, Register::L),
            PrefixedInstruction::RES_2_HL => self.RES_b_r16(2, RegisterPair::HL),
            PrefixedInstruction::RES_2_A => self.RES_b_r8(2, Register::A),
            PrefixedInstruction::RES_3_B => self.RES_b_r8(3, Register::B),
            PrefixedInstruction::RES_3_C => self.RES_b_r8(3, Register::C),
            PrefixedInstruction::RES_3_D => self.RES_b_r8(3, Register::D),
            PrefixedInstruction::RES_3_E => self.RES_b_r8(3, Register::E),
            PrefixedInstruction::RES_3_H => self.RES_b_r8(3, Register::H),
            PrefixedInstruction::RES_3_L => self.RES_b_r8(3, Register::L),
            PrefixedInstruction::RES_3_HL => self.RES_b_r16(3, RegisterPair::HL),
            PrefixedInstruction::RES_3_A => self.RES_b_r8(3, Register::A),
            // * 0xA_
            PrefixedInstruction::RES_4_B => self.RES_b_r8(4, Register::B),
            PrefixedInstruction::RES_4_C => self.RES_b_r8(4, Register::C),
            PrefixedInstruction::RES_4_D => self.RES_b_r8(4, Register::D),
            PrefixedInstruction::RES_4_E => self.RES_b_r8(4, Register::E),
            PrefixedInstruction::RES_4_H => self.RES_b_r8(4, Register::H),
            PrefixedInstruction::RES_4_L => self.RES_b_r8(4, Register::L),
            PrefixedInstruction::RES_4_HL => self.RES_b_r16(4, RegisterPair::HL),
            PrefixedInstruction::RES_4_A => self.RES_b_r8(4, Register::A),
            PrefixedInstruction::RES_5_B => self.RES_b_r8(5, Register::B),
            PrefixedInstruction::RES_5_C => self.RES_b_r8(5, Register::C),
            PrefixedInstruction::RES_5_D => self.RES_b_r8(5, Register::D),
            PrefixedInstruction::RES_5_E => self.RES_b_r8(5, Register::E),
            PrefixedInstruction::RES_5_H => self.RES_b_r8(5, Register::H),
            PrefixedInstruction::RES_5_L => self.RES_b_r8(5, Register::L),
            PrefixedInstruction::RES_5_HL => self.RES_b_r16(5, RegisterPair::HL),
            // * 0xB_
            PrefixedInstruction::RES_5_A => self.RES_b_r8(5, Register::A),
            PrefixedInstruction::RES_6_B => self.RES_b_r8(6, Register::B),
            PrefixedInstruction::RES_6_C => self.RES_b_r8(6, Register::C),
            PrefixedInstruction::RES_6_D => self.RES_b_r8(6, Register::D),
            PrefixedInstruction::RES_6_E => self.RES_b_r8(6, Register::E),
            PrefixedInstruction::RES_6_H => self.RES_b_r8(6, Register::H),
            PrefixedInstruction::RES_6_L => self.RES_b_r8(6, Register::L),
            PrefixedInstruction::RES_6_HL => self.RES_b_r16(6, RegisterPair::HL),
            PrefixedInstruction::RES_6_A => self.RES_b_r8(6, Register::A),
            PrefixedInstruction::RES_7_B => self.RES_b_r8(7, Register::B),
            PrefixedInstruction::RES_7_C => self.RES_b_r8(7, Register::C),
            PrefixedInstruction::RES_7_D => self.RES_b_r8(7, Register::D),
            PrefixedInstruction::RES_7_E => self.RES_b_r8(7, Register::E),
            PrefixedInstruction::RES_7_H => self.RES_b_r8(7, Register::H),
            PrefixedInstruction::RES_7_L => self.RES_b_r8(7, Register::L),
            PrefixedInstruction::RES_7_HL => self.RES_b_r16(7, RegisterPair::HL),
            PrefixedInstruction::RES_7_A => self.RES_b_r8(7, Register::A),
            // * 0xC_
            PrefixedInstruction::SET_0_B => self.SET_b_r8(0, Register::B),
            PrefixedInstruction::SET_0_C => self.SET_b_r8(0, Register::C),
            PrefixedInstruction::SET_0_D => self.SET_b_r8(0, Register::D),
            PrefixedInstruction::SET_0_E => self.SET_b_r8(0, Register::E),
            PrefixedInstruction::SET_0_H => self.SET_b_r8(0, Register::H),
            PrefixedInstruction::SET_0_L => self.SET_b_r8(0, Register::L),
            PrefixedInstruction::SET_0_HL => self.SET_b_r16(0, RegisterPair::HL),
            PrefixedInstruction::SET_0_A => self.SET_b_r8(0, Register::A),
            PrefixedInstruction::SET_1_B => self.SET_b_r8(1, Register::B),
            PrefixedInstruction::SET_1_C => self.SET_b_r8(1, Register::C),
            PrefixedInstruction::SET_1_D => self.SET_b_r8(1, Register::D),
            PrefixedInstruction::SET_1_E => self.SET_b_r8(1, Register::E),
            PrefixedInstruction::SET_1_H => self.SET_b_r8(1, Register::H),
            PrefixedInstruction::SET_1_L => self.SET_b_r8(1, Register::L),
            PrefixedInstruction::SET_1_HL => self.SET_b_r16(1, RegisterPair::HL),
            PrefixedInstruction::SET_1_A => self.SET_b_r8(1, Register::A),
            // * 0xD_
            PrefixedInstruction::SET_2_B => self.SET_b_r8(2, Register::B),
            PrefixedInstruction::SET_2_C => self.SET_b_r8(2, Register::C),
            PrefixedInstruction::SET_2_D => self.SET_b_r8(2, Register::D),
            PrefixedInstruction::SET_2_E => self.SET_b_r8(2, Register::E),
            PrefixedInstruction::SET_2_H => self.SET_b_r8(2, Register::H),
            PrefixedInstruction::SET_2_L => self.SET_b_r8(2, Register::L),
            PrefixedInstruction::SET_2_HL => self.SET_b_r16(2, RegisterPair::HL),
            PrefixedInstruction::SET_2_A => self.SET_b_r8(2, Register::A),
            PrefixedInstruction::SET_3_B => self.SET_b_r8(3, Register::B),
            PrefixedInstruction::SET_3_C => self.SET_b_r8(3, Register::C),
            PrefixedInstruction::SET_3_D => self.SET_b_r8(3, Register::D),
            PrefixedInstruction::SET_3_E => self.SET_b_r8(3, Register::E),
            PrefixedInstruction::SET_3_H => self.SET_b_r8(3, Register::H),
            PrefixedInstruction::SET_3_L => self.SET_b_r8(3, Register::L),
            PrefixedInstruction::SET_3_HL => self.SET_b_r16(3, RegisterPair::HL),
            PrefixedInstruction::SET_3_A => self.SET_b_r8(3, Register::A),
            // * 0xE_
            PrefixedInstruction::SET_4_B => self.SET_b_r8(4, Register::B),
            PrefixedInstruction::SET_4_C => self.SET_b_r8(4, Register::C),
            PrefixedInstruction::SET_4_D => self.SET_b_r8(4, Register::D),
            PrefixedInstruction::SET_4_E => self.SET_b_r8(4, Register::E),
            PrefixedInstruction::SET_4_H => self.SET_b_r8(4, Register::H),
            PrefixedInstruction::SET_4_L => self.SET_b_r8(4, Register::L),
            PrefixedInstruction::SET_4_HL => self.SET_b_r16(4, RegisterPair::HL),
            PrefixedInstruction::SET_4_A => self.SET_b_r8(4, Register::A),
            PrefixedInstruction::SET_5_B => self.SET_b_r8(5, Register::B),
            PrefixedInstruction::SET_5_C => self.SET_b_r8(5, Register::C),
            PrefixedInstruction::SET_5_D => self.SET_b_r8(5, Register::D),
            PrefixedInstruction::SET_5_E => self.SET_b_r8(5, Register::E),
            PrefixedInstruction::SET_5_H => self.SET_b_r8(5, Register::H),
            PrefixedInstruction::SET_5_L => self.SET_b_r8(5, Register::L),
            PrefixedInstruction::SET_5_HL => self.SET_b_r16(5, RegisterPair::HL),
            PrefixedInstruction::SET_5_A => self.SET_b_r8(5, Register::A),
            // * 0xF_
            PrefixedInstruction::SET_6_B => self.SET_b_r8(6, Register::B),
            PrefixedInstruction::SET_6_C => self.SET_b_r8(6, Register::C),
            PrefixedInstruction::SET_6_D => self.SET_b_r8(6, Register::D),
            PrefixedInstruction::SET_6_E => self.SET_b_r8(6, Register::E),
            PrefixedInstruction::SET_6_H => self.SET_b_r8(6, Register::H),
            PrefixedInstruction::SET_6_L => self.SET_b_r8(6, Register::L),
            PrefixedInstruction::SET_6_HL => self.SET_b_r16(6, RegisterPair::HL),
            PrefixedInstruction::SET_6_A => self.SET_b_r8(6, Register::A),
            PrefixedInstruction::SET_7_B => self.SET_b_r8(7, Register::B),
            PrefixedInstruction::SET_7_C => self.SET_b_r8(7, Register::C),
            PrefixedInstruction::SET_7_D => self.SET_b_r8(7, Register::D),
            PrefixedInstruction::SET_7_E => self.SET_b_r8(7, Register::E),
            PrefixedInstruction::SET_7_H => self.SET_b_r8(7, Register::H),
            PrefixedInstruction::SET_7_L => self.SET_b_r8(7, Register::L),
            PrefixedInstruction::SET_7_HL => self.SET_b_r16(7, RegisterPair::HL),
            PrefixedInstruction::SET_7_A => self.SET_b_r8(7, Register::A),
        }
    }
}